### ISSUE TITLE
Issue: autolv.datatypes.AutoLVError: '<COMObject <unknown>>' not array like

### ISSUE THREAD

**Issue by LawsonGu** [l-johnston/autolv#8]
When I open a VI(Only one graph in front/block diagram) like below: then error happened
![image](https://github.com/l-johnston/autolv/assets/101655210/1fb5982c-2844-40f7-a6a2-f9257993240a)

Notice that this graph is a Waveform type, not double array.

Traceback (most recent call last):
  File "c:\test\First_autolv\myFirst_autolv.py", line 31, in <module>
    vi.run()
  File "C:\test\First_autolv\.venv\lib\site-packages\autolv\interface.py", line 280, in run
    asyncio.run(task)
  File "C:\Users\lawgu\.pyenv\pyenv-win\versions\3.10.0-win32\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lawgu\.pyenv\pyenv-win\versions\3.10.0-win32\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\lawgu\.pyenv\pyenv-win\versions\3.10.0-win32\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "C:\test\First_autolv\.venv\lib\site-packages\autolv\interface.py", line 236, in _task
    await asyncio.gather(self._run(), self._spinner())
  File "C:\test\First_autolv\.venv\lib\site-packages\autolv\interface.py", line 219, in _run
    ctrl.value = value
  File "C:\test\First_autolv\.venv\lib\site-packages\autolv\datatypes.py", line 380, in __setattr__
    raise AutoLVError(f"'{value}' not array like")
autolv.datatypes.AutoLVError: '<COMObject <unknown>>' not array like

Here is the Python code with autolv
![image](https://github.com/l-johnston/autolv/assets/101655210/84f4d897-0c3e-4cc0-a3d4-cf7702c7d2f4)

You could see that exection stop in Line 31. I know that we have announced that autolv doesn't support waveform type. But we should give out correct information to users and better don't exit code workflow here.

BTW, happy to see if line 31 replace with vi() it could work

Unfortunately, vi.read_controls seeing the same issue if the VI contains Waveform graph and clsuter.

**Comment by l-johnston** [comment]
@LawsonGu For these unsupported controls like Waveform Data Type, I can issue a logging.Logger.warning() and remove them from the internal data structure containing the controls. This will allow the VI to execute. Here's an example:
![image](https://github.com/l-johnston/autolv/assets/17813788/2e52b46d-302d-4bf2-bf6e-02a8733799e4)

Is this the desired behavior?

**Comment by LawsonGu** [comment]
Yes, I let close this issue if you finish that.
